# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-logger}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cyril Mougel"]
  s.date = %q{2010-05-03}
  s.description = %q{Log request and error on Logger send it by settings}
  s.email = %q{cyril@yeastymobs.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/sinatra/request-logger.rb",
     "lib/sinatra/sinatra-logger.rb",
     "test/helper.rb",
     "test/test_sinatra-logger.rb"
  ]
  s.homepage = %q{http://github.com/shingara/sinatra-logger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Log all request and error on Logger}
  s.test_files = [
    "test/helper.rb",
     "test/test_sinatra-logger.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 1.0.0"])
  end
end

